version: '3.8'

services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydatabase
    ports:
      - "3305:3306"

#docker run -d --name clickhouse-server -p 8123:8123 -p 9000:9000 yandex/clickhouse-server
